<?php

namespace Lilocon\WechatBundle\Repository;

/**
 * WechatUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WechatUserRepository extends \Doctrine\ORM\EntityRepository
{
}
